wandb_version: 1

learning_rate:
  desc: null
  value: 0.0009
dataset_pretrain:
  desc: null
  value: OpenOrca
dataset_finetune:
  desc: null
  value: null
max_steps:
  desc: null
  value: 5000
max_finetune_steps:
  desc: null
  value: 10000
warmup_steps:
  desc: null
  value: 715
val_loss_steps:
  desc: null
  value: 20
compile:
  desc: null
  value: true
total_batch_size:
  desc: null
  value: 16
batch_size:
  desc: null
  value: 16
block_size:
  desc: null
  value: 512
n_layers:
  desc: null
  value: 12
n_heads:
  desc: null
  value: 12
d_model:
  desc: null
  value: 768
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722469342
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.10.9
      5: 0.17.3
      8:
      - 5
      13: linux-x86_64
